export enum QueryNames {
  BOM_INFORMATION_QUERY = 'BOM_INFORMATION_QUERY',
  BOM_MATERIAL_INFORMATION_QUERY = 'BOM_MATERIAL_INFORMATION_QUERY',
  BOM_CHANGE_COMPONENTS_QUERY = 'BOM_CHANGE_COMPONENTS_QUERY',
  BOM_QUERY = 'BOM_QUERY',
  BOM_SPLIT_QUERY = 'BOM_SPLIT_QUERY',
  BOM_COMMON_SIZE_QUERY = 'BOM_COMMON_SIZE_QUERY',
  BOM_FG_OPTION_QUERY = 'BOM_FG_OPTION_QUERY',
  BOM_SIZE_SUB_QUERY = 'BOM_SIZE_SUB_QUERY',
}
