FROM 374320175743.dkr.ecr.ap-southeast-1.amazonaws.com/rapid-base:latest as base
FROM node:14.17.5 as build
WORKDIR /usr/src/app
COPY --from=base /usr/src/app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM 374320175743.dkr.ecr.ap-southeast-1.amazonaws.com/rapid-production:latest as prod
WORKDIR /usr/src/app
RUN rm package*.json
copy package.json .
COPY --from=build /usr/src/app/dist ./dist
CMD ["npm", "run", "start:prod"]