version: 1.0
provider:
  name: openfaas
  gateway: OPENFAAS_GATAWAY_URL
functions:
  sales-customer-order-service:
    lang: dockerfile
    handler: ./
    image: 328680294982.dkr.ecr.ap-southeast-1.amazonaws.com/rapid/rapid-example-service:DOCKER_IMAGE_TAG
