apiVersion: apps/v1
kind: Deployment
metadata:
  name: JOB_BASE_NAME
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JOB_BASE_NAME
  template:
    metadata:
      labels:
        app: JOB_BASE_NAME
    spec:
      containers:
      - name: JOB_BASE_NAME
        livenessProbe:
          tcpSocket:
            port: 3080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 3 
